force-app/main/default/objects/Apex_Code_Coverage_Class_Level__c/Apex_Code_Coverage_Class_Level__c.object-meta.xml
<CustomObject>
    <label>Apex Code Coverage (Class Level)</label>
    <nameField>
        <displayFormat>CR-{000}</displayFormat>
        <label>Apex Code Coverage ( Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Code Coverage (Class Level)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Code_Coverage_Class_Level__c/fields/Apex_Test_Run_Container__c.field-meta.xml
<CustomField>
    <fullName>Apex_Test_Run_Container__c</fullName>
    <label>Apex Test Run Container</label>
    <referenceTo>Apex_Test_Run_Container__c</referenceTo>
    <relationshipLabel>Apex Code Coverage (Class Level)</relationshipLabel>
    <relationshipName>Apex_Code_Coverage_Class_Level</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Apex_Code_Coverage_Method_Level__c/Apex_Code_Coverage_Method_Level__c.object-meta.xml
<CustomObject>
    <label>Apex Code Coverage (Method Level)</label>
    <nameField>
        <displayFormat>MR-{000}</displayFormat>
        <label>Apex Code Coverage (Method Level) Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Code Coverages (Method Level)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Code_Coverage_Method_Level__c/fields/Apex_Test_Run_Container__c.field-meta.xml
<CustomField>
    <fullName>Apex_Test_Run_Container__c</fullName>
    <label>Apex Test Run Container</label>
    <referenceTo>Apex_Test_Run_Container__c</referenceTo>
    <relationshipLabel>Apex Code Coverages (Method Level)</relationshipLabel>
    <relationshipName>Apex_Code_Coverages_Method_Level</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Apex_Test_Run_Container__c/Apex_Test_Run_Container__c.object-meta.xml
<CustomObject>
    <label>Apex Test Run Container</label>
    <nameField>
        <displayFormat>TR-{000}</displayFormat>
        <label>Apex Test Run Container Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Test Run Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Test_Run_Container__c/fields/Is_Result_Updated__c.field-meta.xml
<CustomField>
    <fullName>Is_Result_Updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Result Updated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ApexTestAutoRunQueable.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* This is the class that is used to processing after the callout is done to get the ApexCodeCoverage
*
* Here records are inserted into Apex_Code_Coverage_Method_Level__c and Apex_Code_Coverage_Class_Level__c
* records
*
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Abhijit Debadutta
* @modifiedBy     Abhijit Debadutta
* @maintainedBy   Abhijit Debadutta
* @version        1.0
* @created        2022-05-24
* @modified       
* @systemLayer    Invocation | Service (x) | Utility | Selector | Domain | Test
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* vX.X            <author>
* YYYY-MM-DD      <Description>
*
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
public with sharing class ApexTestAutoRunQueable implements Queueable, Database.AllowsCallouts {
    
    public String containerId;

    /************************************************************************************************
    * ───────────────────────────────────────────────────────────────────────────────────────────────┐
    * This is the contructor where the data send to constructor is set on the class variables
    * ────────────────────────────────────────────────────────────────────────────────────────────────
    * @param    containerId   Type:String
    * @return   -----        
    * ───────────────────────────────────────────────────────────────────────────────────────────────┘
    */
    public ApexTestAutoRunQueable(String containerId) {
        this.containerId = containerId;
    }
    
    /************************************************************************************************
    * ───────────────────────────────────────────────────────────────────────────────────────────────┐
    * This method inerts records into Apex_Code_Coverage_Method_Level__c and 
    * Apex_Code_Coverage_Class_Level__c records
    * ────────────────────────────────────────────────────────────────────────────────────────────────
    * @param    context      Type:QueueableContext
    * @return   -----        
    * ───────────────────────────────────────────────────────────────────────────────────────────────┘
    */
    public void execute(QueueableContext context) {
        //REST callout to Tooling API object ApexCodeCoverage and create records in Apex Code Coverage objects
        List<Apex_Code_Coverage_Method_Level__c> methodCov = ApexTestAutoRunUtility.getCoverageDetails(containerId);

        //create Method Level Coverage records
        ApexTestAutoRunUtility.insertCTestCodeCovDetails(methodCov,containerId);

        //update the container records to indicate results are inserted
        update new Apex_Test_Run_Container__c(Id = containerId, Is_Result_Updated__c = true);

        //send Email with attached PDF
        ApexTestAutoRunUtility.generatePDFAndSendMail(containerId);
    }
}