force-app/main/default/objects/Apex_Code_Coverage_Class_Level__c/Apex_Code_Coverage_Class_Level__c.object-meta.xml
<CustomObject>
    <label>Apex Code Coverage (Class Level)</label>
    <nameField>
        <displayFormat>CR-{000}</displayFormat>
        <label>Apex Code Coverage ( Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Code Coverage (Class Level)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Code_Coverage_Class_Level__c/fields/Apex_Test_Run_Container__c.field-meta.xml
<CustomField>
    <fullName>Apex_Test_Run_Container__c</fullName>
    <label>Apex Test Run Container</label>
    <referenceTo>Apex_Test_Run_Container__c</referenceTo>
    <relationshipLabel>Apex Code Coverage (Class Level)</relationshipLabel>
    <relationshipName>Apex_Code_Coverage_Class_Level</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Apex_Code_Coverage_Class_Level__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <formula>Number_of_Lines_Covered__c / (Number_of_Lines_Covered__c +  Number_of_Lines_Uncovered__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coverage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Apex_Code_Coverage_Class_Level__c/fields/Lines_Uncovered__c.field-meta.xml
<CustomField>
    <fullName>Lines_Uncovered__c</fullName>
    <label>Lines Uncovered</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Test_Class_Run_Result__c/Apex_Test_Class_Run_Result__c.object-meta.xml
<CustomObject>
    <label>Apex Test Class Run Result</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Apex Test Class Run Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Test Class Run Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Test_Class_Run_Result__c/fields/Apex_Test_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Test_Class_Name__c</fullName>
    <label>Apex Test Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Test_Class_Run_Result__c/fields/Apex_Test_Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Test_Method_Name__c</fullName>
    <label>Apex Test Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Test_Class_Run_Result__c/fields/Apex_Test_Run_Container__c.field-meta.xml
<CustomField>
    <fullName>Apex_Test_Run_Container__c</fullName>
    <label>Apex Test Run Container</label>
    <referenceTo>Apex_Test_Run_Container__c</referenceTo>
    <relationshipLabel>Apex Test Class Run Results</relationshipLabel>
    <relationshipName>Apex_Test_Class_Run_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Apex_Test_Class_Run_Result__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>Mapped to the Message field of the ApexTestResult</description>
    <label>Exception Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Test_Class_Run_Result__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Test_Run_Container__c/Apex_Test_Run_Container__c.object-meta.xml
<CustomObject>
    <label>Apex Test Run Container</label>
    <nameField>
        <displayFormat>TR-{000}</displayFormat>
        <label>Apex Test Run Container Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Test Run Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DisplayTestClassResultController.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* This class will generate the test class run result as a PDF
*
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Abhijit Debadutta
* @modifiedBy     Abhijit Debadutta
* @maintainedBy   Abhijit Debadutta
* @version        1.0
* @created        2022-05-28
* @modified       
* @systemLayer    Invocation | Service(x) | Utility | Selector | Domain | Test
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* vX.X            <author>
* YYYY-MM-DD      <Description>
*
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
public with sharing class DisplayTestClassResultController {

    public String sandboxname{get;set;} //stores sandbox name to display the same on the report
    public List<Apex_Test_Class_Run_Result__c> testRunRes {get;set;} //list of apex test run result
    public List<Apex_Code_Coverage_Class_Level__c> classCoverage {get;set;} //list of class level coverages

    /************************************************************************************************
    * ───────────────────────────────────────────────────────────────────────────────────────────────┐
    * This is the constructor of the class
    * 
    * Here the data to be displayed is fetched
    * ────────────────────────────────────────────────────────────────────────────────────────────────
    * @param    ---     N/A
    * @return   ---     N/A
    * ───────────────────────────────────────────────────────────────────────────────────────────────┘
    */
    public DisplayTestClassResultController() {
        //Initialize Class level variables
        sandboxname = UserInfo.getUserName().substringAfterLast('@');

        //get the page parameters and confirm that apex test run container id is present
        Map<String, String> parameters = ApexPages.currentPage().getParameters();
        if(!parameters.containsKey('containerId')){
            ApexPages.Message errMessage = new ApexPages.Message(ApexPages.Severity.ERROR, 'Apex Test Run Container Id not provided');
            ApexPages.addMessage(errMessage);
        }
        else{
            String containerId = parameters.get('containerId');
            //get the conainer related data i.e. Test Run Result and ClassCoverage
            testRunRes = [Select Id,Apex_Test_Class_Name__c,Apex_Test_Method_Name__c,Outcome__c,Exception_Message__c from Apex_Test_Class_Run_Result__c where Apex_Test_Run_Container__c =:containerId];
            classCoverage = [Select Id,Apex_Class_Name__c,Coverage__c,Lines_Uncovered__c from Apex_Code_Coverage_Class_Level__c where Apex_Test_Run_Container__c =:containerId order by Coverage__c ASC];
        }
    }
}